// <auto-generated />
namespace SuperWarmart.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixedErrors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedErrors));
        
        string IMigrationMetadata.Id
        {
            get { return "202011222327005_FixedErrors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
